filipecalegario/awesome-generative-ai

- README.md
Thanks for the awesome list! We are the makers of https://www.aiimagegenerator.org and we would love to add it to your list, under Stable Diffusion Deployed Web Tools 🙂
> Add aiimagegenerator.org to Stable Diffusion Deployed Web Tools category

- README.md
Add part 2 of famous fast.ai course 2023 by Jeremy Howard. In this course Jeremy implement stable diffusion from scratch with python.
> Add fast.ai newest course notebooks and youtube video links

- README.md
Nekton is a service that will help to automate the workflows using AI. You can describe your workflow in plain text steps, and then those steps will be automated by Nekton and executed in the cloud.
> Add online tool to list

- README.md
Hi, I'd love to add my free AI story generator tool to your awesome collection
> Add aistorygenerator.org

- README.md
Added prodia.com
Prodia is easy to beginners because there's no limit for free accounts. It doesn't even requires sign up.
> Added prodia.com

- README.md
AI-generated visual prototyping and editing platform, supports 2D and 3D models, combined with LLM (Large Language Model) for fast editing.
https://github.com/CloudOrc/SolidUI
Minimalist process, concise design
Various 2D legends
Various 3D legends
Various 3D scenes
Support multiple data sources
Support Huggingface space
Support plug-in robot
Support SolidUI-Model
Support Large Language Model
Containerized deployment
Code co-construction (front-end, Java, python, etc.)
Community co-construction (content management)
All kinds of donations are available
Users can also
This is, I, I am free, so free and free energy to maintain and initiate
> add SolidUI AI visualization

- README.md
Hi, I'd love to add my free AI voice generator to your list
> Add aivoicegenerator.org to the text-to-speech list

- README.md
Adding ComicsMaker.ai for creating comics using Stable Diffusion online
> Add ComicsMaker.ai

- README.md
Adding the following relevant resources in the awesome list.
1. Under Langchain
Embedchain - 3.9K stars
It helps create ChatGPT like bots with only a few lines of Code.
Repo Link: https://github.com/embedchain/embedchain
2. Under Courses and Education Materials
- https://www.cloudskillsboost.google/course_templates/536
- https://www.deeplearning.ai/courses/generative-ai-with-llms/
> update: Langchain Tools & 2 Courses

- README.md
> Add Tailor

- README.md
proposal to add ainave.com in the list
> feat: added ainave

- README.md
> Add Chatpdf.so

- README.md
I hope the commit is self-explanatory!
Happy to provide more context if needed.
Thanks,
Filip
> feat: add DataCamp's become an AI developer series

- README.md
Hi @filipecalegario, I added BrainSoup, a native multi-LLM client for Windows with advanced features such as local document indexing, RAG, multi-modality, multi-agent automation, code interpreter, sandboxed file system and the ability for agents to interact with the local system via customizable events and tools. More information can be found [here](https://www.nurgo-software.com/products/brainsoup).
I kindly ask for your review of this PR. Thanks for creating this awesome list!
> Add BrainSoup to Multi-agents

- README.md
Adding poto.ai to Stable Diffusion Deployed Web Tools List
> feat: add POTO.AI

- README.md
Free AI Tools for Social Media Marketing
> Add Lunroo.com

- README.md
MemFree is a hybrid AI search engine that simultaneously performs searches on your personal knowledge base (such as bookmarks, notes, documents, etc.) and the Internet.
- Hybrid AI Search Engine
- One-Click Chrome Bookmarks Sync and Index
- Support multiple traditional search engines as source
- Self-hosted Super Fast Serverless Vector Database
- Self-hosted Super Fast Local Embedding and Rerank Service
- Full Code Open Source
- One-Click Deployment On Production
> Add memfree to AI search

- README.md
Hi, @filipecalegario Nice work, I wonder if it is ok to merge this PR, thanks!
> add Indico LLM Leaderboard

- README.md
PageGen is an AI Web Page Generator. PageGen leverages the most powerful AI model (Claude 3.5 Sonnet) and the most popular frontend frameworks (React + Tailwind + Shadcn UI) to generate production-ready UI pages in just seconds.
Supports generating web pages with a single click from text, screenshots, and templates.
Supported Features:
🖥️ Real-time UI Preview: What-you-see-is-what-you-get development experience
🔍 AI-Driven Content Search: Utilize AI to enrich UI content
📑 Rich Page Templates: Quickly generate pages from templates with one click
🖼 Image Generation: Generate UI interfaces almost identical to screenshots
⚛️ React + TailWind + Shadcn UI Integration
🚀 One-Click Deployment of Generated UI Pages
🎯 One-Click Theme Color Switching
📱 Responsive Code and Preview: Both code …
> Add PageGen AI to README.md

- README.md
Add comet-ml/opik to README.md
Signed-off-by: Abby Morgan abigailm@comet.com
> Add comet-ml/opik to README.md

- README.md
Adds AI Tool List to the Generative AI Tools Directories section
> Add AI Tool List

- README.md
Hi :) 
Proposing to add Lunary, an open-source LLMOps platform and Abso, a TypeScript library for easily calling LLMs.
Thanks!
> Add Lunary and Abso

- README.md
Hi!
Thank you for putting up this awesome list! ⚡
I’m excited to share my latest repo with you. PerchanceStory is an AI-based interactive story generator, which generates ever-changing story endings with endless possibilities based on simple user-provided input. 
You can check out the product here: https://perchancestory.com/
It would be great to be featured 🙏🏼
> Add PerchanceStory
